/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseAdvancedRouteImport } from './routes/warehouse-advanced'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as SuspendedRouteImport } from './routes/suspended'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as OnboardingBrandingRouteImport } from './routes/onboarding/branding'
import { Route as DeveloperSaasRouteImport } from './routes/developer.saas'
import { Route as DeliveryOrderIdRouteImport } from './routes/delivery.$orderId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPushRouteImport } from './routes/admin.push'
import { Route as AdminPurchasesRouteImport } from './routes/admin.purchases'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLiveTrackingRouteImport } from './routes/admin.live-tracking'
import { Route as AdminDebtsRouteImport } from './routes/admin.debts'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminChatbotRouteImport } from './routes/admin.chatbot'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as AccountPasswordRouteImport } from './routes/account.password'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiPublicSendPushRouteImport } from './routes/api/public/send-push'
import { Route as ApiAdminTenantsRouteImport } from './routes/api/admin/tenants'
import { Route as ApiAdminFeaturesRouteImport } from './routes/api/admin/features'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'
import { Route as ApiAdminTenantsTenantIdMobileBuildRouteImport } from './routes/api/admin/tenants.$tenantId.mobile-build'
import { Route as ApiAdminTenantsIdSuspendRouteImport } from './routes/api/admin/tenants.$id.suspend'
import { Route as ApiAdminTenantsIdResumeRouteImport } from './routes/api/admin/tenants.$id.resume'

const WarehouseAdvancedRoute = WarehouseAdvancedRouteImport.update({
  id: '/warehouse-advanced',
  path: '/warehouse-advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const SuspendedRoute = SuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const OnboardingBrandingRoute = OnboardingBrandingRouteImport.update({
  id: '/onboarding/branding',
  path: '/onboarding/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSaasRoute = DeveloperSaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeliveryOrderIdRoute = DeliveryOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => DeliveryRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPushRoute = AdminPushRouteImport.update({
  id: '/admin/push',
  path: '/admin/push',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/admin/purchases',
  path: '/admin/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/admin/offers',
  path: '/admin/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveTrackingRoute = AdminLiveTrackingRouteImport.update({
  id: '/admin/live-tracking',
  path: '/admin/live-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDebtsRoute = AdminDebtsRouteImport.update({
  id: '/admin/debts',
  path: '/admin/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatbotRoute = AdminChatbotRouteImport.update({
  id: '/admin/chatbot',
  path: '/admin/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPasswordRoute = AccountPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AccountRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendPushRoute = ApiPublicSendPushRouteImport.update({
  id: '/api/public/send-push',
  path: '/api/public/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTenantsRoute = ApiAdminTenantsRouteImport.update({
  id: '/api/admin/tenants',
  path: '/api/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFeaturesRoute = ApiAdminFeaturesRouteImport.update({
  id: '/api/admin/features',
  path: '/api/admin/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const ApiAdminTenantsTenantIdMobileBuildRoute =
  ApiAdminTenantsTenantIdMobileBuildRouteImport.update({
    id: '/$tenantId/mobile-build',
    path: '/$tenantId/mobile-build',
    getParentRoute: () => ApiAdminTenantsRoute,
  } as any)
const ApiAdminTenantsIdSuspendRoute =
  ApiAdminTenantsIdSuspendRouteImport.update({
    id: '/$id/suspend',
    path: '/$id/suspend',
    getParentRoute: () => ApiAdminTenantsRoute,
  } as any)
const ApiAdminTenantsIdResumeRoute = ApiAdminTenantsIdResumeRouteImport.update({
  id: '/$id/resume',
  path: '/$id/resume',
  getParentRoute: () => ApiAdminTenantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/accounting': typeof AccountingRoute
  '/cart': typeof CartRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/developer': typeof DeveloperRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspended': typeof SuspendedRoute
  '/warehouse': typeof WarehouseRoute
  '/warehouse-advanced': typeof WarehouseAdvancedRoute
  '/account/password': typeof AccountPasswordRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/debts': typeof AdminDebtsRoute
  '/admin/live-tracking': typeof AdminLiveTrackingRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/push': typeof AdminPushRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/delivery/$orderId': typeof DeliveryOrderIdRoute
  '/developer/saas': typeof DeveloperSaasRoute
  '/onboarding/branding': typeof OnboardingBrandingRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/api/admin/features': typeof ApiAdminFeaturesRoute
  '/api/admin/tenants': typeof ApiAdminTenantsRouteWithChildren
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/admin/tenants/$id/resume': typeof ApiAdminTenantsIdResumeRoute
  '/api/admin/tenants/$id/suspend': typeof ApiAdminTenantsIdSuspendRoute
  '/api/admin/tenants/$tenantId/mobile-build': typeof ApiAdminTenantsTenantIdMobileBuildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/accounting': typeof AccountingRoute
  '/cart': typeof CartRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/developer': typeof DeveloperRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspended': typeof SuspendedRoute
  '/warehouse': typeof WarehouseRoute
  '/warehouse-advanced': typeof WarehouseAdvancedRoute
  '/account/password': typeof AccountPasswordRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/debts': typeof AdminDebtsRoute
  '/admin/live-tracking': typeof AdminLiveTrackingRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/push': typeof AdminPushRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/delivery/$orderId': typeof DeliveryOrderIdRoute
  '/developer/saas': typeof DeveloperSaasRoute
  '/onboarding/branding': typeof OnboardingBrandingRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/api/admin/features': typeof ApiAdminFeaturesRoute
  '/api/admin/tenants': typeof ApiAdminTenantsRouteWithChildren
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/admin/tenants/$id/resume': typeof ApiAdminTenantsIdResumeRoute
  '/api/admin/tenants/$id/suspend': typeof ApiAdminTenantsIdSuspendRoute
  '/api/admin/tenants/$tenantId/mobile-build': typeof ApiAdminTenantsTenantIdMobileBuildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/accounting': typeof AccountingRoute
  '/cart': typeof CartRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/developer': typeof DeveloperRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspended': typeof SuspendedRoute
  '/warehouse': typeof WarehouseRoute
  '/warehouse-advanced': typeof WarehouseAdvancedRoute
  '/account/password': typeof AccountPasswordRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/debts': typeof AdminDebtsRoute
  '/admin/live-tracking': typeof AdminLiveTrackingRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/push': typeof AdminPushRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/delivery/$orderId': typeof DeliveryOrderIdRoute
  '/developer/saas': typeof DeveloperSaasRoute
  '/onboarding/branding': typeof OnboardingBrandingRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/api/admin/features': typeof ApiAdminFeaturesRoute
  '/api/admin/tenants': typeof ApiAdminTenantsRouteWithChildren
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/admin/tenants/$id/resume': typeof ApiAdminTenantsIdResumeRoute
  '/api/admin/tenants/$id/suspend': typeof ApiAdminTenantsIdSuspendRoute
  '/api/admin/tenants/$tenantId/mobile-build': typeof ApiAdminTenantsTenantIdMobileBuildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/accounting'
    | '/cart'
    | '/delivery'
    | '/developer'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/portfolio'
    | '/products'
    | '/sitemap.xml'
    | '/suspended'
    | '/warehouse'
    | '/warehouse-advanced'
    | '/account/password'
    | '/admin/about'
    | '/admin/banners'
    | '/admin/branding'
    | '/admin/categories'
    | '/admin/chatbot'
    | '/admin/customers'
    | '/admin/debts'
    | '/admin/live-tracking'
    | '/admin/messages'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/push'
    | '/admin/reports'
    | '/admin/tenants'
    | '/admin/users'
    | '/delivery/$orderId'
    | '/developer/saas'
    | '/onboarding/branding'
    | '/orders/$orderId'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/api/admin/features'
    | '/api/admin/tenants'
    | '/api/public/send-push'
    | '/api/webhooks/stripe'
    | '/api/admin/tenants/$id/resume'
    | '/api/admin/tenants/$id/suspend'
    | '/api/admin/tenants/$tenantId/mobile-build'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/accounting'
    | '/cart'
    | '/delivery'
    | '/developer'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/portfolio'
    | '/products'
    | '/sitemap.xml'
    | '/suspended'
    | '/warehouse'
    | '/warehouse-advanced'
    | '/account/password'
    | '/admin/about'
    | '/admin/banners'
    | '/admin/branding'
    | '/admin/categories'
    | '/admin/chatbot'
    | '/admin/customers'
    | '/admin/debts'
    | '/admin/live-tracking'
    | '/admin/messages'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/push'
    | '/admin/reports'
    | '/admin/tenants'
    | '/admin/users'
    | '/delivery/$orderId'
    | '/developer/saas'
    | '/onboarding/branding'
    | '/orders/$orderId'
    | '/admin'
    | '/admin/customers/$customerId'
    | '/api/admin/features'
    | '/api/admin/tenants'
    | '/api/public/send-push'
    | '/api/webhooks/stripe'
    | '/api/admin/tenants/$id/resume'
    | '/api/admin/tenants/$id/suspend'
    | '/api/admin/tenants/$tenantId/mobile-build'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/accounting'
    | '/cart'
    | '/delivery'
    | '/developer'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/portfolio'
    | '/products'
    | '/sitemap.xml'
    | '/suspended'
    | '/warehouse'
    | '/warehouse-advanced'
    | '/account/password'
    | '/admin/about'
    | '/admin/banners'
    | '/admin/branding'
    | '/admin/categories'
    | '/admin/chatbot'
    | '/admin/customers'
    | '/admin/debts'
    | '/admin/live-tracking'
    | '/admin/messages'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/push'
    | '/admin/reports'
    | '/admin/tenants'
    | '/admin/users'
    | '/delivery/$orderId'
    | '/developer/saas'
    | '/onboarding/branding'
    | '/orders/$orderId'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/api/admin/features'
    | '/api/admin/tenants'
    | '/api/public/send-push'
    | '/api/webhooks/stripe'
    | '/api/admin/tenants/$id/resume'
    | '/api/admin/tenants/$id/suspend'
    | '/api/admin/tenants/$tenantId/mobile-build'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AccountingRoute: typeof AccountingRoute
  CartRoute: typeof CartRoute
  DeliveryRoute: typeof DeliveryRouteWithChildren
  DeveloperRoute: typeof DeveloperRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuspendedRoute: typeof SuspendedRoute
  WarehouseRoute: typeof WarehouseRoute
  WarehouseAdvancedRoute: typeof WarehouseAdvancedRoute
  AdminAboutRoute: typeof AdminAboutRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminChatbotRoute: typeof AdminChatbotRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDebtsRoute: typeof AdminDebtsRoute
  AdminLiveTrackingRoute: typeof AdminLiveTrackingRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminPushRoute: typeof AdminPushRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OnboardingBrandingRoute: typeof OnboardingBrandingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminFeaturesRoute: typeof ApiAdminFeaturesRoute
  ApiAdminTenantsRoute: typeof ApiAdminTenantsRouteWithChildren
  ApiPublicSendPushRoute: typeof ApiPublicSendPushRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse-advanced': {
      id: '/warehouse-advanced'
      path: '/warehouse-advanced'
      fullPath: '/warehouse-advanced'
      preLoaderRoute: typeof WarehouseAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suspended': {
      id: '/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof SuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/onboarding/branding': {
      id: '/onboarding/branding'
      path: '/onboarding/branding'
      fullPath: '/onboarding/branding'
      preLoaderRoute: typeof OnboardingBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/saas': {
      id: '/developer/saas'
      path: '/saas'
      fullPath: '/developer/saas'
      preLoaderRoute: typeof DeveloperSaasRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/delivery/$orderId': {
      id: '/delivery/$orderId'
      path: '/$orderId'
      fullPath: '/delivery/$orderId'
      preLoaderRoute: typeof DeliveryOrderIdRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/push': {
      id: '/admin/push'
      path: '/admin/push'
      fullPath: '/admin/push'
      preLoaderRoute: typeof AdminPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/admin/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live-tracking': {
      id: '/admin/live-tracking'
      path: '/admin/live-tracking'
      fullPath: '/admin/live-tracking'
      preLoaderRoute: typeof AdminLiveTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/debts': {
      id: '/admin/debts'
      path: '/admin/debts'
      fullPath: '/admin/debts'
      preLoaderRoute: typeof AdminDebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chatbot': {
      id: '/admin/chatbot'
      path: '/admin/chatbot'
      fullPath: '/admin/chatbot'
      preLoaderRoute: typeof AdminChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/password': {
      id: '/account/password'
      path: '/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AccountPasswordRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-push': {
      id: '/api/public/send-push'
      path: '/api/public/send-push'
      fullPath: '/api/public/send-push'
      preLoaderRoute: typeof ApiPublicSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tenants': {
      id: '/api/admin/tenants'
      path: '/api/admin/tenants'
      fullPath: '/api/admin/tenants'
      preLoaderRoute: typeof ApiAdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/features': {
      id: '/api/admin/features'
      path: '/api/admin/features'
      fullPath: '/api/admin/features'
      preLoaderRoute: typeof ApiAdminFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/api/admin/tenants/$tenantId/mobile-build': {
      id: '/api/admin/tenants/$tenantId/mobile-build'
      path: '/$tenantId/mobile-build'
      fullPath: '/api/admin/tenants/$tenantId/mobile-build'
      preLoaderRoute: typeof ApiAdminTenantsTenantIdMobileBuildRouteImport
      parentRoute: typeof ApiAdminTenantsRoute
    }
    '/api/admin/tenants/$id/suspend': {
      id: '/api/admin/tenants/$id/suspend'
      path: '/$id/suspend'
      fullPath: '/api/admin/tenants/$id/suspend'
      preLoaderRoute: typeof ApiAdminTenantsIdSuspendRouteImport
      parentRoute: typeof ApiAdminTenantsRoute
    }
    '/api/admin/tenants/$id/resume': {
      id: '/api/admin/tenants/$id/resume'
      path: '/$id/resume'
      fullPath: '/api/admin/tenants/$id/resume'
      preLoaderRoute: typeof ApiAdminTenantsIdResumeRouteImport
      parentRoute: typeof ApiAdminTenantsRoute
    }
  }
}

interface AccountRouteChildren {
  AccountPasswordRoute: typeof AccountPasswordRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountPasswordRoute: AccountPasswordRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface DeliveryRouteChildren {
  DeliveryOrderIdRoute: typeof DeliveryOrderIdRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryOrderIdRoute: DeliveryOrderIdRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

interface DeveloperRouteChildren {
  DeveloperSaasRoute: typeof DeveloperSaasRoute
}

const DeveloperRouteChildren: DeveloperRouteChildren = {
  DeveloperSaasRoute: DeveloperSaasRoute,
}

const DeveloperRouteWithChildren = DeveloperRoute._addFileChildren(
  DeveloperRouteChildren,
)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface AdminCustomersRouteChildren {
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface ApiAdminTenantsRouteChildren {
  ApiAdminTenantsIdResumeRoute: typeof ApiAdminTenantsIdResumeRoute
  ApiAdminTenantsIdSuspendRoute: typeof ApiAdminTenantsIdSuspendRoute
  ApiAdminTenantsTenantIdMobileBuildRoute: typeof ApiAdminTenantsTenantIdMobileBuildRoute
}

const ApiAdminTenantsRouteChildren: ApiAdminTenantsRouteChildren = {
  ApiAdminTenantsIdResumeRoute: ApiAdminTenantsIdResumeRoute,
  ApiAdminTenantsIdSuspendRoute: ApiAdminTenantsIdSuspendRoute,
  ApiAdminTenantsTenantIdMobileBuildRoute:
    ApiAdminTenantsTenantIdMobileBuildRoute,
}

const ApiAdminTenantsRouteWithChildren = ApiAdminTenantsRoute._addFileChildren(
  ApiAdminTenantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AccountingRoute: AccountingRoute,
  CartRoute: CartRoute,
  DeliveryRoute: DeliveryRouteWithChildren,
  DeveloperRoute: DeveloperRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuspendedRoute: SuspendedRoute,
  WarehouseRoute: WarehouseRoute,
  WarehouseAdvancedRoute: WarehouseAdvancedRoute,
  AdminAboutRoute: AdminAboutRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminChatbotRoute: AdminChatbotRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDebtsRoute: AdminDebtsRoute,
  AdminLiveTrackingRoute: AdminLiveTrackingRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminPushRoute: AdminPushRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  OnboardingBrandingRoute: OnboardingBrandingRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminFeaturesRoute: ApiAdminFeaturesRoute,
  ApiAdminTenantsRoute: ApiAdminTenantsRouteWithChildren,
  ApiPublicSendPushRoute: ApiPublicSendPushRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
